paths:
/companies:
  post:
    summary: 회사 등록
    tags:
      - Companies
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              companyName:
                type: string
                example: "DEF 자동차"
              companyCode:
                type: string
                example: "DEF001"
            required:
              - companyName
              - companyCode
    responses:
      "201":
        description: 회사 등록 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                companyName:
                  type: string
                  example: "카메이트"
                companyCode:
                  type: string
                  example: "CM12345"
                userCount:
                  type: integer
                  example: 3
      "400":
        description: 잘못된 요청입니다
      "401":
        description: 인증 실패 - 관리자 권한 필요

  get:
    summary: 회사 목록 조회
    tags:
      - Companies
    security:
      - bearerAuth: []
    parameters:
      - name: page
        in: query
        description: 현재 페이지 번호
        required: false
        schema:
          type: integer
          example: 1
      - name: limit
        in: query
        description: 페이지당 보여줄 회사 수
        required: false
        schema:
          type: integer
          example: 10
    responses:
      "200":
        description: 회사 목록 조회 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPage:
                  type: integer
                  example: 1
                totalPages:
                  type: integer
                  example: 2
                totalItemCount:
                  type: integer
                  example: 6
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      companyName:
                        type: string
                        example: "ABC 자동차"
                      companyCode:
                        type: string
                        example: "ABC001"
                      userCount:
                        type: integer
                        example: 3
      "400":
        description: 잘못된 요청입니다
      "401":
        description: 인증 실패 - 관리자 권한 필요

/companies/users:
  get:
    summary: 회사별 유저 조회
    tags:
      - Companies
    security:
      - bearerAuth: []
    parameters:
      - name: page
        in: query
        description: 현재 페이지 번호
        required: false
        schema:
          type: integer
          example: 1
      - name: pageSize
        in: query
        description: 페이지 당 아이템 수
        required: false
        schema:
          type: integer
          example: 10
      - name: searchBy
        in: query
        description: 검색 기준
        required: false
        schema:
          type: string
          enum: [companyName, name, email]
          example: "name"
      - name: keyword
        in: query
        description: 검색어
        required: false
        schema:
          type: string
          example: "이상혁"
    responses:
      "200":
        description: 회사 사용자 조회 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPage:
                  type: integer
                  example: 1
                totalPages:
                  type: integer
                  example: 5
                totalItemCount:
                  type: integer
                  example: 42
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: "이상혁"
                      email:
                        type: string
                        example: "admin@carsales.com"
                      companyName:
                        type: string
                        example: "ABC 자동차"
      "400":
        description: 잘못된 요청입니다
      "401":
        description: 인증 실패 - 권한 필요

  patch:
    summary: 회사 정보 수정
    tags:
      - Companies
    security:
      - bearerAuth: []
    parameters:
      - name: comapanyId
        in: path
        description: 회사 ID
        required: true
        schema:
          type: integer
          example: 1
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              companyName:
                type: string
                example: "ABC자동차"
              companyCode:
                type: string
                example: "ABC002"
    responses:
      "200":
        description: 회사 정보 수정 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                companyName:
                  type: string
                  example: "ABC 자동차"
                companyCode:
                  type: string
                  example: "ABC001"
                userCount:
                  type: integer
                  example: 3
      "400":
        description: 잘못된 요청입니다.
      "401":
        description: 인증 실패 - 관리자 권한 필요합니다.
      "404":
        description: 존재하지 않는 회사입니다.

/companies/{companyId}:
  delete:
    summary: 회사 삭제
    tags:
      - Companies
    security:
      - bearerAuth: []
    parameters:
      - name: companyId
        in: path
        description: 회사 ID
        required: true
        schema:
          type: integer
          example: 1
    responses:
      "200":
        description: 회사 삭제 성공
      "400":
        description: 잘못된 요청입니다.
      "401":
        description: 인증 실패 - 관리자 권한 필요합니다.
      "404":
        description: 존재하지 않는 회사입니다.
