openapi: 3.0.0
info:
  title: DearCarmate API
  version: 1.0.0
  description: DearCarmate 프로젝트 - API 문서
servers:
  - url: http://localhost:3001

paths:
  # 회사
  /companies:
    $ref: "./companies.swagger.yaml#/companies"
  /companies/users:
    $ref: "./companies.swagger.yaml#/users"
  /companies/{companyId}:
    $ref: "./companies.swagger.yaml#/companyId"

  # 계약서
  /contractDocuments:
    $ref: "./contractDocument.swagger.yaml#/contractDocuments"
  /contractDocuments/draft:
    $ref: "./contractDocument.swagger.yaml#/draft"
  /contractDocuments/upload:
    $ref: "./contractDocument.swagger.yaml#/upload"
  /contractDocuments/{contractDocumentId}/download:
    $ref: "./contractDocument.swagger.yaml#/contractDocumentId/download"

  # 차량
  /cars:
    $ref: "./car.swagger.yaml#/cars"
  /cars/{carId}:
    $ref: "./car.swagger.yaml#/carId"
  /cars/upload:
    $ref: "./car.swagger.yaml#/upload"
